---
project:
  type: book
  output-dir: docs
book:
  title: OWASP Machine Learning Security Top 10 (2023 edition)
  output-file: OWASP Machine Learning Security Top 10
  site-url: https://mltop10.info
  favicon: favicon.png
  cover-image: cover.png
  search: true
  repo-url: https://github.com/OWASP/www-project-machine-learning-security-top-10
  repo-subdir: 2023/
  repo-branch: master
  repo-actions: [edit, issue]
  downloads: [pdf]
  reader-mode: true
  open-graph: true
  twitter-card:
    creator: '@OWASP'
    image: cover.png
  navbar:
    title: OWASP Machine Learning Security Top 10 (2023 edition)
    logo: favicon.png
    pinned: true
  chapters:
    - index.md
    - notice.md
    - about_owasp.md
    - part: Top 10 2023 List
      chapters:
        - ML01_2023-Adversarial_Attack.md
        - ML02_2023-Data_Poisoning_Attack.md
        - ML03_2023-Model_Inversion_Attack.md
        - ML04_2023-Membership_Inference_Attack.md
        - ML05_2023-Model_Stealing.md
        - ML06_2023-Corrupted_Packages.md
        - ML07_2023-Transfer_Learning_Attack.md
        - ML08_2023-Model_Skewing.md
        - ML09_2023-Output_Integrity_Attack.md
        - ML10_2023-Neural_Net_Reprogramming.md
    - acknowledgements.md
    - glossary.md
format:
  html:
    theme:
      light: cosmo
      # dark: cyborg
    toc: true
    toc-title: Page Contents
    number-sections: false
    anchor-sections: true
    # embed-resources: true
    smooth-scroll: true
    # link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    comments:
      hypothesis:
        theme: clean
        openSidebar: true
  pdf:
    documentclass: report
    # classoptions: twocolumn
    # toc: false
    papersize: a4
    page-layout: full
    number-sections: false
    geometry:
      - top=20mm
      - left=10mm
      - right=10mm
      - heightrounded
      # pdf-engine: prince
  epub:
    cover-image: cover.png
